image: docker:stable


.build_job: &build_template
  stage: build
  before_script:
    # - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git-registry.mittelab.org
    - export CONTAINER_IMAGE="git-registry.mittelab.org/$CI_PROJECT_PATH/$image_tag"
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest $extra_args $workdir
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest


build:llvm-toolchain:
  <<: *build_template
  variables:
    image_tag: llvm-7-arm
    workdir: llvm-toolchain
    extra_args: --build-arg LLVM_VERSION=70 --build-arg LLVM_TARGETS=ARM
