stages:
  - build

.build-definition: &build-template
  image: docker:stable
  stage: build
  before_script:
   - apk add --no-cache --update bash
  script:
    - bash autobuild.sh \
      --image-tag "rpi-cross-${RASPBIAN_VERSION}" \
      --build-arg RASPBIAN_VERSION="${RASPBIAN_VERSION}" \
      ./rpi-cross/Dockerfile

build:stretch:
  <<: *build-template
  variables:
    RASPBIAN_VERSION: stretch

build:buster:
  <<: *build-template
  variables:
    RASPBIAN_VERSION: buster
