build:llvm7-arm:
  image: docker:stable
  stage: build
  script:
    - ls
    - bash autobuild.sh
      --image-tag llvm7-arm
      --build-arg LLVM_VERSION=70
      --build-arg LLVM_TARGETS=ARM
      --build-arg LLVM_PROJECTS=""
      --build-arg LLVM_TOOLS="clang lld"
      src/llvm-toolchain.dockerfile


# build:cross-libcxx-armv6:
#   image: docker:stable
#   stage: build
#   script:
#     - bash autobuild.sh
#       --image-tag cross-libcxx-armv6
#       --build-arg LLVM_VERSION=70
#       --build-arg TARGET_TRIPLE=arm-linux-gnueabihf
#       --build-arg TARGET_ARCH_FLAGS="-march=armv6 -mfloat-abi=hard -mfpu=vfp"
#       --build-arg BASE_BUILDER_IMAGE=$CI_REGISTRY/$CI_PROJECT_PATH/llvm7-arm
#       src/cross-libcxx.dockerfile
