image: docker:stable


.build_job: &build_template
  stage: build
  before_script:
    # - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - export CONTAINER_IMAGE="$CI_REGISTRY/$CI_PROJECT_PATH/$image_tag"
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build
        --cache-from $CONTAINER_IMAGE:latest
        --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA
        --tag $CONTAINER_IMAGE:latest
        --file $dockerfile
        $extra_args
        $workdir
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest


build:llvm7-arm:
  <<: *build_template
  variables:
    image_tag: llvm7-arm
    workdir: src
    dockerfile: src/llvm-toolchain.dockerfile
    extra_args: --build-arg LLVM_VERSION=70
      --build-arg LLVM_TARGETS=ARM
      --build-arg LLVM_PROJECTS=""
      --build-arg LLVM_TOOLS="clang lld"


build:cross-libcxx-armv6:
  <<: *build_template
  variables:
    image_tag: cross-libcxx-armv6
    workdir: src
    dockerfile: src/cross-libcxx.dockerfile
    extra_args: --build-arg LLVM_VERSION=70
      --build-arg TARGET_TRIPLE=arm-linux-gnueabihf
      --build-arg TARGET_ARCH_FLAGS="-march=armv6 -mfloat-abi=hard -mfpu=vfp"
      --build-arg BASE_BUILDER_IMAGE=$CI_REGISTRY/$CI_PROJECT_PATH/llvm7-arm
