stages:
  - build
  - unbundle


build:rpi-cross:
  image: docker:stable
  stage: build
  before_script:
   - apk add --no-cache --update bash
  script:
    - bash autobuild.sh
      --image-tag rpi-cross
      src/rpi-cross.dockerfile


build:rpi-cross-libcxx:
  image: docker:stable
  stage: build
  before_script:
   - apk add --no-cache --update bash
  script:
    - bash autobuild.sh
      --image-tag rpi-cross-libcxx
      --build-arg LLVM_VERSION=60
      --build-arg TOOLCHAIN_FILE=/usr/share/RPiToolchain.cmake
      --build-arg RPI_CROSS_IMAGE=$CI_REGISTRY/$CI_PROJECT_PATH/rpi-cross
      --build-arg SYSROOT=/usr/share/rpi-sysroot
      src/rpi-cross-libcxx.dockerfile


unbundle:rpi-sysroot:
  stage: unbundle
  image: $CI_REGISTRY/$CI_PROJECT_PATH/rpi-cross-libcxx
  script:
    - mv /usr/share/rpi-sysroot rpi-sysroot
    - du -sh rpi-sysroot
  artifacts:
    paths:
      - rpi-sysroot
