image: docker:stable

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: git-registry.mittelab.org/$CI_PROJECT_PATH/raspbian-cmake


before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git-registry.mittelab.org

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest
